name: Build Next.js site

on:
  # this makes it callable from other repos
  workflow_call:
    inputs:
      build-directory:
        description: 'Directory to build (e.g., out, dist, etc.)'
        type: string
        required: false
        default: './out'
      artifact-name:
        description: 'Name of the artifact to download'
        type: string
        required: false
        default: 'build-artifact'
      hosting-service:
        description: 'Name of the artifact to download'
        type: string
        required: false
        default: 'github-pages'
      working-directory:
        description: 'working directory of the app'
        type: string
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: 'pnpm'

      - name: Install dependencies
        working-directory: ${{inputs.working-directory}}
        run: pnpm install

      - name: Setup Pages
        if: ${{ inputs.hosting-service == 'github-pages' }}
        id: setup_pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: next

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            .next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-

      - name: Build with Next.js
        working-directory: ${{inputs.working-directory}} 
        run: pnpm run build
        env:
          PAGES_BASE_PATH: ${{ steps.setup_pages.outputs.base_path }}

      - name: Upload artifact
        if: ${{ inputs.hosting-service == 'github-pages' }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ inputs.build-directory }}

      - name: Upload build artifact
        if: ${{ inputs.hosting-service != 'github-pages' }}
        uses: actions/upload-artifact@v4
        with:
            name: ${{ inputs.artifact-name }}
            path: ${{inputs.build-directory}}