name: Build and Test Go App

on:
  # this makes it callable from other repos
  workflow_call:
    inputs:
      app-name:
        description: 'name of the app'
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build Go binary
        run: go build -o ${{inputs.app-name}} ./cmd/${{inputs.app-name}}

      #- name: Run tests
      #  run: go test ./...