name: Deploy site to GitHub Pages

on:
  workflow_call:
    inputs:
      build-directory:
        description: 'Directory to build (e.g., out, dist, etc.)'
        required: false
        type: string
        default: './out'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          # Specify the path to the artifact or directory to deploy
          path: ${{ inputs.build-directory }}