name: Deploy Container to fly.io

on:
  # this makes it callable from other repos
  workflow_call:
    inputs:
      app-name:
        description: 'name of the app'
        type: string
        required: true
      registry-username:
        description: 'GitHub Container Registry username (GitHub username)'
        type: string
        required: true

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        uses: superfly/flyctl-actions@1.4
        with:
          args: "deploy -a propertytoolsbyrotabackend --image ghcr.io/malcolmdzimati/propertytoolsbyrotabackend:latest --remote-only"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
