name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      app-name:
        description: 'Name of the Docker image/app'
        type: string
        required: true
      registry-username:
        description: 'Container registry username'
        type: string
        required: true
      dockerfile-path:
        description: 'Working directory for Docker context'
        type: string
        required: true
        default: '.'
      artifact-name:
        description: 'Name of the artifact to download'
        type: string
        required: false
        default: 'build-artifact'

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ./build

      - name: Copy Dockerfile into build directory
        run: cp -r ${{ inputs.dockerfile-path }} ./build/

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ inputs.registry-username }}/${{ inputs.app-name }}:latest ./build

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ inputs.registry-username }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: docker push ghcr.io/${{ inputs.registry-username }}/${{ inputs.app-name }}:latest